import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { Sidebar } from "@/components/Sidebar";
import { Header } from "@/ui/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Don Saude",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex bg-[#FFF] w-full h-full">
          <Sidebar />
          <Header />
          <div className="flex-grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
